name: Create a new release

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      calver: ${{ steps.tag.outputs.calver }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Tag the repository
        id: tag
        run: |
          # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          CALVER=$(date +'%y.%m.%d.%H')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "calver=$CALVER" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG

  convert:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        language: ["ace", "ach", "aar", "afr", "aka", "sqi", "amh", "anw", "ara", "arg", "hye", "asm", "ast", "aym", "aze", "ban", "bam", "bjn", "bak", "eus", "bar", "bel", "bem", "ben", "bih", "bik", "bpy", "bos", "bre", "bug", "bul", "bua", "mya", "cat", "ceb", "bcl", "ckb", "che", "zho", "chv", "cos", "hrv", "ces", "dan", "prs", "div", "diq", "nld", "dyu", "emk", "mhr", "ydd", "arz", "eml", "eng", "myv", "epo", "est", "ewe", "ext", "fao", "hif", "fin", "fon", "fra", "ful", "glg", "gan", "lug", "kat", "deu", "glk", "gom", "grn", "guj", "hat", "khk", "hau", "heb", "hil", "hin", "hun", "ibb", "isl", "ido", "ibo", "ilo", "ind", "ina", "ile", "pes", "gle", "ita", "jpn", "jav", "kbd", "kbp", "kea", "kab", "kal", "kan", "krc", "kas", "csb", "kaz", "khm", "kik", "kin", "kir", "mkw", "kom", "koi", "kon", "knn", "kng", "kor", "kur", "ksh", "lad", "lao", "lat", "lav", "lij", "lim", "lin", "lit", "lmo", "ngl", "nds", "dsb", "lgg", "lup", "lus", "ltz", "mkd", "mad", "mai", "kde", "mlg", "msa", "mal", "mlt", "cmn", "glv", "mri", "mar", "mzn", "cdo", "nan", "min", "xmf", "mwl", "ell", "mon", "mos", "nav", "ndo", "nap", "nep", "new", "pcm", "azj", "frr", "sme", "uzn", "nor", "nob", "nno", "nya", "nyn", "oci", "ori", "orm", "oss", "pam", "pag", "pan", "pap", "nso", "fas", "pfl", "pms", "plt", "pol", "pnt", "por", "fuc", "pus", "que", "ron", "roh", "rom", "run", "rus", "rue", "ksw", "smi", "sgs", "san", "skr", "srd", "sco", "seh", "srp", "hbs", "sna", "scn", "szl", "snd", "sin", "slk", "slv", "som", "snk", "nbl", "sot", "spa", "ekk", "lvs", "zsm", "suk", "sun", "sus", "swh", "swa", "ssw", "swe", "gsw", "tgl", "tgk", "tam", "tat", "tel", "tha", "bod", "tir", "tem", "tiv", "als", "tso", "tsn", "tcy", "tum", "tur", "tuk", "tyv", "udm", "uig", "ukr", "hsb", "urd", "uzb", "ven", "vec", "vie", "vls", "vol", "vro", "wln", "war", "cym", "fry", "mrj", "pnb", "wol", "wuu", "xho", "sah", "yid", "yor", "zea", "zha", "zul"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run main script
        run: python main.py ${{ matrix.language }}

      - name: Upload dictionary files
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.prepare.outputs.calver }}
          tag_name: ${{ needs.prepare.outputs.tag }}
          prerelease: true
          generate_release_notes: true
          files: "*.zip"
