name: Create a new release

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      calver: ${{ steps.tag.outputs.calver }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Tag the repository
        id: tag
        run: |
          # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          CALVER=$(date +'%y.%m.%d.%H')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "calver=$CALVER" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG

  convert:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        language: ["srp", "hrv"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Run main script
        run: python main.py ${{ matrix.language }}

      - name: Upload dictionary files
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.prepare.outputs.calver }}
          tag_name: ${{ needs.prepare.outputs.tag }}
          prerelease: true
          generate_release_notes: true
          files: "*.zip"
